### ISSUE TITLE
Somehow Test.py doesn't work

### ISSUE THREAD

**Issue by momsu** [MomsFriendlyRobotCompany/adafruit-precision-nxp-9-dof#1]
I'm using on a Raspi board , this show up when I run the `accel() ` , `gyro()` will shows up a similar error as well. I'm pretty sure my i2c works fine and it has detect 0x1f and 0x21

  I2C Device: 0x21
  Bus: 1
 
0x21 13 3
Traceback (most recent call last):
  File "test.py", line 50, in <module>
    gyro()
  File "test.py", line 13, in gyro
    f = FXAS21002(GYRO_RANGE_250DPS)
  File "build/bdist.linux-armv7l/egg/nxp_imu/FXAS21002.py", line 83, in __init__
Exception: Could not find FXAS21002C gyro

**Comment by walchko** [comment]
sorry, I am still writing this (and a couple other libraries) for a class I am teaching. I noticed an issue with the gyro also last night. If you can wait a day or so, I will see what's up. It is probably something silly I am doing. I also need to get rid of some of the debugging info printed out.

**Comment by walchko** [comment]
On your raspberry pi, issue this `sudo i2cdetect -y 1`, you should get something like this:
``` bash
$ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 1f 
20: -- 21 -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- 
```
This will scan bus 1 and see all of the i2c sensors on it. Then paste the output into a comment. I am curious if you are using a different bus for some reason.
thanks!

**Comment by momsu** [comment]
I got the same result. Still can't figure out what's wrong :(
